[RFC] API Versioning
galaxyproject/galaxy-helm pull request #255
Opened 2021-03-13 15:14 UTC by ksuderman

Addresses #242 

I will delete this PR and submit a proper one shortly,  but I wanted a quick review by @almahmoud to verify this is what you have in mind.  Once I am able to bend Kubernetes and Helm to my will I can do some proper testing under the various Kubernetes versions (or at least I think I will...)

2021-03-14 08:29 UTC, almahmoud approved these changes
This looks great!

2021-03-14 20:32 UTC, almahmoud requested changes
I resolved conflicts with the latest version given the helm3 PR got merged. Just a few changes and this should be good for merging.

2021-03-14 20:32 UTC, almahmoud commented on galaxy/templates/ingress-activity-canary.yaml
>  metadata:
Need to change the paths form below for the new API version:
```
            backend:
              service:
                name: {{ $fullName }}-nginx
                port:
                  number: {{ $servicePort }}
```

roughly

2021-03-14 20:32 UTC, almahmoud commented on galaxy/templates/ingress.yaml
>  metadata:
Similar to above comment, need to change the paths form below.

```
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
```
roughly

2021-03-15 04:04 UTC, almahmoud requested changes

2021-03-15 04:04 UTC, almahmoud commented on galaxy/templates/ingress.yaml
> +              servicePort: {{ $servicePort }}
```suggestion
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
```

2021-03-15 04:04 UTC, almahmoud commented on galaxy/values.yaml
> +  storageClass: nfs
We don't want a default storageClass so that it uses the cluster default if not set.

2021-03-15 04:04 UTC, almahmoud commented on galaxy/values.yaml
> +  galaxyDatabasePassword: galaxydbpassword
We shouldn't hardcode the password. It's convenient for dev but not a good default overall

2021-03-15 04:46 UTC, almahmoud commented on galaxy/values.yaml
> +  tag: 21.01
We're probably just waiting for 4.0.0 to change default to `21.01`

2021-03-15 05:13 UTC, nuwang commented
It doesn't quite work for me locally. Could it be the dry run?
```
~/work/galaxy-helm/galaxy(ksuderman-242-api-versioning ✗) kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2-rc2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-18T17:34:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

~/work/galaxy-helm/galaxy(ksuderman-242-api-versioning ✗) helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}

~/work/galaxy-helm/galaxy(ksuderman-242-api-versioning ✗) helm install --dry-run --debug test .
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/nuwan/work/galaxy-helm/galaxy

Error: template: galaxy/templates/priorityclass-job.yaml:8:5: executing "galaxy/templates/priorityclass-job.yaml" at <fail "This chart requires Kubernetes v1.14 or later">: error calling fail: This chart requires Kubernetes v1.14 or later
helm.go:81: [debug] template: galaxy/templates/priorityclass-job.yaml:8:5: executing "galaxy/templates/priorityclass-job.yaml" at <fail "This chart requires Kubernetes v1.14 or later">: error calling fail: This chart requires Kubernetes v1.14 or later
```

2021-03-15 05:14 UTC, nuwang commented
Looks like that's not the reason either:
```
~/work/galaxy-helm/galaxy(ksuderman-242-api-versioning ✗) helm install  test .
Error: template: galaxy/templates/priorityclass-job.yaml:8:5: executing "galaxy/templates/priorityclass-job.yaml" at <fail "This chart requires Kubernetes v1.14 or later">: error calling fail: This chart requires Kubernetes v1.14 or later
```

2021-03-15 06:09 UTC, merged

2021-03-15 06:09 UTC, nuwang commented
Thanks @ksuderman This fixes the deployments and works as expected.